import type { Notary } from '../types/notary.types';

export const MOCK_NOTARIES: Notary[] = [
  {
    id: 'NT-001',
    firstName: 'Nguyen',
    lastName: 'Van A',
    name: 'Nguyen Van A',
    email: 'nguyen.vana@example.com',
    phone: '0901234567',
    capability: 'RON, Mobile Notary',
    state: 'California',
    expiryDate: '2025-12-31',
    branch: 'Main Office',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nguyen',
    commissionNumber: 'CA-10293847',
    addressLine1: '456 Sunshine Blvd',
    city: 'Los Angeles',
    zipCode: '90001',
    languages: 'English, Vietnamese',
    rating: 4.9,
    totalReviews: 200,
    dob: '1985-05-15',
    commissionStatus: 'Active',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid',
    insuranceExpiry: '2025-05-22',
  },
  {
    id: 'NT-002',
    firstName: 'Joey',
    lastName: 'Duc',
    name: 'Joey Duc',
    email: 'duc.joey@gmail.com',
    phone: '213-456-7890',
    capability: 'Loan Signing',
    state: 'Texas',
    expiryDate: '2024-06-15',
    branch: 'North Branch',
    status: 'Expired',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Joey',
    commissionNumber: 'TX-20394857',
    addressLine1: '789 Star Lane',
    city: 'Austin',
    zipCode: '73301',
    languages: 'English',
    rating: 4.7,
    totalReviews: 89,
    dob: '1990-08-22',
    commissionStatus: 'Expired',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-003',
    firstName: 'Robert',
    lastName: 'Brown',
    name: 'Robert Brown',
    email: 'robert.b@example.com',
    phone: '(555) 345-6789',
    capability: 'Mobile Notary',
    state: 'Arizona',
    expiryDate: '2025-08-20',
    branch: 'West side',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    commissionNumber: 'AZ-39485712',
    addressLine1: '123 Desert Road',
    city: 'Phoenix',
    zipCode: '85001',
    languages: 'English',
    rating: 4.5,
    totalReviews: 45,
    dob: '1982-11-05',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-004',
    firstName: 'Jessica',
    lastName: 'Brown',
    name: 'Jessica Brown',
    email: 'jessica.b@mail.com',
    phone: '213-456-7890',
    capability: 'Mobile Notary, RON, Loan Signing',
    state: 'Florida',
    expiryDate: '2027-07-20',
    branch: 'Santa Clara',
    status: 'Expired',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    commissionNumber: 'FL-49586712',
    addressLine1: '567 Palm Ave',
    city: 'Miami',
    zipCode: '33101',
    languages: 'English, Spanish',
    dob: '1988-02-14',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-005',
    firstName: 'David',
    lastName: 'Jones',
    name: 'David Jones',
    email: 'd.jones@mail.com',
    phone: '(555) 567-8901',
    capability: 'Mobile Notary, Apostille Support',
    state: 'Washington',
    expiryDate: '2022-09-01',
    branch: 'Harris',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    commissionNumber: 'WA-59684712',
    addressLine1: '890 Rainier View',
    city: 'Seattle',
    zipCode: '98101',
    languages: 'English',
    dob: '1975-12-01',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-006',
    firstName: 'Sarah',
    lastName: 'Garcia',
    name: 'Sarah Garcia',
    email: 'sarah.g@mail.com',
    phone: '(555) 678-9012',
    capability: 'RON, Loan Signing',
    state: 'Nevada',
    expiryDate: '2028-01-10',
    branch: 'Dallas',
    status: 'Expired',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    commissionNumber: 'NV-69785712',
    addressLine1: '234 Strip View',
    city: 'Las Vegas',
    zipCode: '89101',
    languages: 'English, Spanish',
    dob: '1992-05-30',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-007',
    firstName: 'Robert',
    lastName: 'Miller',
    name: 'Robert Miller',
    email: 'r.miller@mail.com',
    phone: '(555) 789-0123',
    capability: 'Mobile Notary, RON',
    state: 'Arizona',
    expiryDate: '2025-11-11',
    branch: 'Tarrant',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RobertM',
    commissionNumber: 'AZ-79886712',
    addressLine1: '789 Saguaro Way',
    city: 'Tucson',
    zipCode: '85701',
    languages: 'English',
    dob: '1980-07-20',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-008',
    firstName: 'Ashley',
    lastName: 'Davis',
    name: 'Ashley Davis',
    email: 'ashley.d@mail.com',
    phone: '(555) 890-1234',
    capability: 'Mobile Notary, Loan Signing',
    state: 'Illinois',
    expiryDate: '2027-02-02',
    branch: 'Travis',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashley',
    commissionNumber: 'IL-89987712',
    addressLine1: '345 Windy City Plaza',
    city: 'Chicago',
    zipCode: '60601',
    languages: 'English',
    dob: '1987-09-15',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-009',
    firstName: 'William',
    lastName: 'Rodriguez',
    name: 'William Rodriguez',
    email: 'w.rodriguez@mail.com',
    phone: '(555) 901-2345',
    capability: 'RON, Loan Signing',
    state: 'Ohio',
    expiryDate: '2026-06-06',
    branch: 'Miami-Dade',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William',
    commissionNumber: 'OH-91088712',
    addressLine1: '123 Buckeye Lane',
    city: 'Columbus',
    zipCode: '43201',
    languages: 'English, Spanish',
    dob: '1984-03-22',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-010',
    firstName: 'Amanda',
    lastName: 'Martinez',
    name: 'Amanda Martinez',
    email: 'amanda.m@mail.com',
    phone: '(555) 012-3456',
    capability: 'Mobile Notary, RON',
    state: 'Michigan',
    expiryDate: '2024-08-08',
    branch: 'Broward',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda',
    commissionNumber: 'MI-02189712',
    addressLine1: '456 Great Lakes Blvd',
    city: 'Detroit',
    zipCode: '48201',
    languages: 'English',
    dob: '1991-11-12',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  }
];
