import type { Notary } from '../types/notary.types';

export const MOCK_NOTARIES: Notary[] = [
  {
    id: 'NT-001',
    firstName: 'James',
    lastName: 'Smith',
    name: 'James Smith',
    email: 'james.smith@example.com',
    phone: '(555) 123-4567',
    capability: 'Mobile, RON',
    state: 'California',
    expiryDate: '2025-12-31',
    branch: 'Main Office',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    commissionNumber: 'CA-10293847',
    addressLine1: '456 Sunshine Blvd',
    city: 'Los Angeles',
    zipCode: '90001',
    languages: 'English, Spanish',
    rating: 4.9,
    totalReviews: 200,
    dob: '1985-05-15',
    commissionStatus: 'Active',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid',
    insuranceExpiry: '2025-05-22',
    commissions: [
      {
        id: '#8829',
        commissionNumber: 'CA-20248847',
        state: 'California',
        issueDate: '2022-08-15',
        expiryDate: '2025-08-15',
        status: 'Valid'
      },
      {
        id: '#8828',
        commissionNumber: 'CA-22248847',
        state: 'California',
        issueDate: '2021-09-17',
        expiryDate: '2024-09-17',
        status: 'Expired'
      }
    ]
  },
  {
    id: 'notary-2',
    firstName: 'Jane',
    lastName: 'Smith',
    name: 'Jane Smith',
    email: 'janesmith@example.com',
    phone: '+1 555-567-8901',
    capability: 'Apostille, Mobile Notary',
    state: 'Texas',
    expiryDate: '2024-11-20',
    branch: 'Austin Branch',
    status: 'Active',
    commissionNumber: 'TX-99887766',
    addressLine1: '456 Austin Ave',
    city: 'Austin',
    zipCode: '73301',
    languages: 'English, Spanish',
    rating: 4.7,
    totalReviews: 89,
    dob: '1990-11-20',
    commissionStatus: 'Active',
    bondStatus: 'Valid',
    insuranceStatus: 'Expired',
    insuranceExpiry: '2024-03-22',
    commissions: [
      {
        id: '#9901',
        commissionNumber: 'TX-55667788',
        state: 'Texas',
        issueDate: '2020-01-10',
        expiryDate: '2024-01-10',
        status: 'Expired'
      }
    ]
  },
  {
    id: 'NT-002',
    firstName: 'Emily',
    lastName: 'Johnson',
    name: 'Emily Johnson',
    email: 'emily.j@example.com',
    phone: '(555) 234-5678',
    capability: 'Loan Signing',
    state: 'Texas',
    expiryDate: '2024-06-15',
    branch: 'North Branch',
    status: 'Expired',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    commissionNumber: 'TX-20394857',
    addressLine1: '789 Star Lane',
    city: 'Austin',
    zipCode: '73301',
    languages: 'English',
    rating: 4.7,
    totalReviews: 89,
    dob: '1990-08-22',
    commissionStatus: 'Expired',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-003',
    firstName: 'Robert',
    lastName: 'Brown',
    name: 'Robert Brown',
    email: 'robert.b@example.com',
    phone: '(555) 345-6789',
    capability: 'Mobile',
    state: 'Arizona',
    expiryDate: '2025-08-20',
    branch: 'West side',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    commissionNumber: 'AZ-39485712',
    addressLine1: '123 Desert Road',
    city: 'Phoenix',
    zipCode: '85001',
    languages: 'English',
    rating: 4.5,
    totalReviews: 45,
    dob: '1982-11-05',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-004',
    firstName: 'Jessica',
    lastName: 'Brown',
    name: 'Jessica Brown',
    email: 'jessica.b@mail.com',
    phone: '(555) 456-7890',
    capability: 'Mobile, RON, Loan Signing',
    state: 'Florida',
    expiryDate: '2027-07-20',
    branch: 'Santa Clara',
    status: 'Deactive',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica',
    commissionNumber: 'FL-49586712',
    addressLine1: '567 Palm Ave',
    city: 'Miami',
    zipCode: '33101',
    languages: 'English, Spanish',
    dob: '1988-02-14',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-005',
    firstName: 'David',
    lastName: 'Jones',
    name: 'David Jones',
    email: 'd.jones@mail.com',
    phone: '(555) 567-8901',
    capability: 'Mobile, Apostille Support',
    state: 'Washington',
    expiryDate: '2022-09-01',
    branch: 'Harris',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    commissionNumber: 'WA-59684712',
    addressLine1: '890 Rainier View',
    city: 'Seattle',
    zipCode: '98101',
    languages: 'English',
    dob: '1975-12-01',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-006',
    firstName: 'Sarah',
    lastName: 'Garcia',
    name: 'Sarah Garcia',
    email: 'sarah.g@mail.com',
    phone: '(555) 678-9012',
    capability: 'RON, Loan Signing',
    state: 'Nevada',
    expiryDate: '2028-01-10',
    branch: 'Dallas',
    status: 'Deactive',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    commissionNumber: 'NV-69785712',
    addressLine1: '234 Strip View',
    city: 'Las Vegas',
    zipCode: '89101',
    languages: 'English, Spanish',
    dob: '1992-05-30',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-007',
    firstName: 'Robert',
    lastName: 'Miller',
    name: 'Robert Miller',
    email: 'r.miller@mail.com',
    phone: '(555) 789-0123',
    capability: 'Mobile, RON',
    state: 'Arizona',
    expiryDate: '2025-11-11',
    branch: 'Tarrant',
    status: 'Deactive',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RobertM',
    commissionNumber: 'AZ-79886712',
    addressLine1: '789 Saguaro Way',
    city: 'Tucson',
    zipCode: '85701',
    languages: 'English',
    dob: '1980-07-20',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-008',
    firstName: 'Ashley',
    lastName: 'Davis',
    name: 'Ashley Davis',
    email: 'ashley.d@mail.com',
    phone: '(555) 890-1234',
    capability: 'Mobile, Loan Signing',
    state: 'Illinois',
    expiryDate: '2027-02-02',
    branch: 'Travis',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ashley',
    commissionNumber: 'IL-89987712',
    addressLine1: '345 Windy City Plaza',
    city: 'Chicago',
    zipCode: '60601',
    languages: 'English',
    dob: '1987-09-15',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-009',
    firstName: 'William',
    lastName: 'Rodriguez',
    name: 'William Rodriguez',
    email: 'w.rodriguez@mail.com',
    phone: '(555) 901-2345',
    capability: 'RON, Loan Signing',
    state: 'Ohio',
    expiryDate: '2026-06-06',
    branch: 'Miami-Dade',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William',
    commissionNumber: 'OH-91088712',
    addressLine1: '123 Buckeye Lane',
    city: 'Columbus',
    zipCode: '43201',
    languages: 'English, Spanish',
    dob: '1984-03-22',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-010',
    firstName: 'Amanda',
    lastName: 'Martinez',
    name: 'Amanda Martinez',
    email: 'amanda.m@mail.com',
    phone: '(555) 012-3456',
    capability: 'Mobile, RON',
    state: 'Michigan',
    expiryDate: '2024-08-08',
    branch: 'Broward',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda',
    commissionNumber: 'MI-02189712',
    addressLine1: '456 Great Lakes Blvd',
    city: 'Detroit',
    zipCode: '48201',
    languages: 'English',
    dob: '1991-11-12',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-011',
    firstName: 'Joseph',
    lastName: 'Hernandez',
    name: 'Joseph Hernandez',
    email: 'j.hernandez@mail.com',
    phone: '(555) 111-2233',
    capability: 'Mobile, Loan Signing',
    state: 'Georgia',
    expiryDate: '2027-12-12',
    branch: 'Orange',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Joseph',
    commissionNumber: 'GA-11223344',
    addressLine1: '789 Peachtree St',
    city: 'Atlanta',
    zipCode: '30301',
    languages: 'English, Spanish',
    dob: '1986-06-18',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-012',
    firstName: 'Melissa',
    lastName: 'Lopez',
    name: 'Melissa Lopez',
    email: 'melissa.l@mail.com',
    phone: '(555) 222-3344',
    capability: 'RON, Apostille Support',
    state: 'North Carolina',
    expiryDate: '2022-03-03',
    branch: 'Palm Beach',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Melissa',
    commissionNumber: 'NC-22334455',
    addressLine1: '234 Blue Ridge Pkwy',
    city: 'Charlotte',
    zipCode: '28201',
    languages: 'English',
    dob: '1989-10-05',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-013',
    firstName: 'Charles',
    lastName: 'Gonzalez',
    name: 'Charles Gonzalez',
    email: 'c.gonzalez@mail.com',
    phone: '(555) 333-4455',
    capability: 'Mobile, RON, Loan Signing',
    state: 'Virginia',
    expiryDate: '2028-04-04',
    branch: 'Kings',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charles',
    commissionNumber: 'VA-33445566',
    addressLine1: '567 Old Dominion Rd',
    city: 'Richmond',
    zipCode: '23219',
    languages: 'English, Spanish',
    dob: '1978-01-30',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-014',
    firstName: 'Nicole',
    lastName: 'Wilson',
    name: 'Nicole Wilson',
    email: 'nicole.w@mail.com',
    phone: '(555) 444-5566',
    capability: 'Mobile',
    state: 'New Jersey',
    expiryDate: '2024-10-10',
    branch: 'Queens',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nicole',
    commissionNumber: 'NJ-44556677',
    addressLine1: '890 Garden State Pkwy',
    city: 'Jersey City',
    zipCode: '07097',
    languages: 'English',
    dob: '1993-04-12',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-015',
    firstName: 'Thomas',
    lastName: 'Anderson',
    name: 'Thomas Anderson',
    email: 't.anderson@mail.com',
    phone: '(555) 555-6677',
    capability: 'RON, Loan Signing',
    state: 'Pennsylvania',
    expiryDate: '2023-07-07',
    branch: 'New York',
    status: 'Deactive',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas',
    commissionNumber: 'PA-55667788',
    addressLine1: '123 Liberty Bell Ln',
    city: 'Philadelphia',
    zipCode: '19101',
    languages: 'English',
    dob: '1981-12-25',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-016',
    firstName: 'Samantha',
    lastName: 'Thomas',
    name: 'Samantha Thomas',
    email: 'samantha.t@mail.com',
    phone: '(555) 666-7788',
    capability: 'Mobile, RON',
    state: 'Massachusetts',
    expiryDate: '2028-02-02',
    branch: 'Bronx',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Samantha',
    commissionNumber: 'MA-66778899',
    addressLine1: '345 Beacon Hill',
    city: 'Boston',
    zipCode: '02108',
    languages: 'English',
    dob: '1990-09-08',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-017',
    firstName: 'Christopher',
    lastName: 'Taylor',
    name: 'Christopher Taylor',
    email: 'c.taylor@mail.com',
    phone: '(555) 777-8899',
    capability: 'Mobile, Loan Signing',
    state: 'Colorado',
    expiryDate: '2027-05-05',
    branch: 'King',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Christopher',
    commissionNumber: 'CO-77889900',
    addressLine1: '567 Mile High Dr',
    city: 'Denver',
    zipCode: '80201',
    languages: 'English',
    dob: '1983-05-14',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-018',
    firstName: 'Elizabeth',
    lastName: 'Moore',
    name: 'Elizabeth Moore',
    email: 'e.moore@mail.com',
    phone: '(555) 888-9900',
    capability: 'RON',
    state: 'Oregon',
    expiryDate: '2026-09-09',
    branch: 'Pierce',
    status: 'Deactive',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elizabeth',
    commissionNumber: 'OR-88990011',
    addressLine1: '890 Rose Garden Ct',
    city: 'Portland',
    zipCode: '97201',
    languages: 'English',
    dob: '1989-11-20',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-019',
    firstName: 'Joshua',
    lastName: 'Jackson',
    name: 'Joshua Jackson',
    email: 'j.jackson@mail.com',
    phone: '(555) 999-0011',
    capability: 'Mobile, RON, Loan Signing',
    state: 'Minnesota',
    expiryDate: '2025-11-11',
    branch: 'Snohomish',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Joshua',
    commissionNumber: 'MN-99001122',
    addressLine1: '123 Lakeshore Dr',
    city: 'Minneapolis',
    zipCode: '55401',
    languages: 'English',
    dob: '1985-08-30',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  },
  {
    id: 'NT-020',
    firstName: 'Lauren',
    lastName: 'Martin',
    name: 'Lauren Martin',
    email: 'lauren.m@mail.com',
    phone: '(555) 000-1122',
    capability: 'Mobile, Apostille Support',
    state: 'Utah',
    expiryDate: '2028-06-06',
    branch: 'Cook',
    status: 'Active',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lauren',
    commissionNumber: 'UT-00112233',
    addressLine1: '456 Red Rock Cyn',
    city: 'Salt Lake City',
    zipCode: '84101',
    languages: 'English',
    dob: '1992-02-14',
    commissionStatus: 'Valid',
    bondStatus: 'Valid',
    insuranceStatus: 'Valid'
  }
];
